services:
  database:
    image: postgres:16
    container_name: ferreteria_alessandro_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: clave123
      POSTGRES_DB: ferreteria_alessandro_db
    volumes:
      - db:/var/lib/postgresql/data

  server:
    depends_on:
      - database
    build: ./backend
    container_name: ferreteria_alessandro_backend
    ports:
      - "3001:3001"
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: ferreteria_alessandro_db
      DB_USER: postgres
      DB_PASSWORD: clave123
      NODE_ENV: development
      JWT_SECRET: ferreteria_alessandro_secret_key_2025
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app/backend

  client:
    build: ./frontend
    container_name: ferreteria_alessandro_frontend
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - WDS_SOCKET_HOST=localhost
      - WDS_SOCKET_PORT=3000
    stdin_open: true
    tty: true
    develop:
      watch:
        - action: sync
          path: ./frontend/src
          target: /app/src

volumes:
  db:
